question_data = {"response_code": 0, "results": [{"category": "Celebrities", "type": "boolean", "difficulty": "medium",
                                                  "question": "Michael Jackson had a pet python named &lsquo;Crusher&rsquo;.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "There are no roads in\/out of Juneau, Alaska.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                                                  "question": "Tennis was once known as Racquetball.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Science: Gadgets", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Music", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "For his performance at ComplexCon 2016 in Long Beach, California, Skrillex revived his &quot;Mothership&quot; set piece for one night only.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "Pistons were added to Minecraft in Beta 1.5.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "In the video game &quot;Transistor&quot;, &quot;Red&quot; is the name of the main character.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Television", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "Klingons respect their disabled comrades, and those who are old, injuried, and helpless.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Science & Nature", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "Sound can travel through a vacuum.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]}]}
